"""Canonical, transport-independent AOMS v2 contracts."""

from aoms.contracts.errors import ErrorCode, ErrorDetail, ErrorResponse
from aoms.contracts.models import (
    ContestEntry,
    ContestResolution,
    ContestState,
    ContestTrigger,
    MemoryKind,
    MemoryRecord,
    IntegrityReport,
    Provenance,
    RecallRequest,
    RecallResult,
    RecallSource,
    ReceiptPruneReport,
    RememberRequest,
    RememberResult,
    SupersedeRequest,
    Scope,
    ScopeContext,
    SearchHit,
    SearchRequest,
    SearchResult,
    WriteDisposition,
)

__all__ = [
    "ContestEntry",
    "ContestResolution",
    "ContestState",
    "ContestTrigger",
    "ErrorCode",
    "ErrorDetail",
    "ErrorResponse",
    "MemoryKind",
    "MemoryRecord",
    "IntegrityReport",
    "Provenance",
    "RecallRequest",
    "RecallResult",
    "RecallSource",
    "ReceiptPruneReport",
    "RememberRequest",
    "RememberResult",
    "SupersedeRequest",
    "Scope",
    "ScopeContext",
    "SearchHit",
    "SearchRequest",
    "SearchResult",
    "WriteDisposition",
]
